[package]
name = "wazzup"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"
description = "Very opinionated Rust WASM project builder"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]

[dependencies]
anyhow = "1.0.70"
axum = { version = "0.6.15", features = ["http2", "ws"] }
cargo-lock = "8.0.3"
clap = { version = "4.2.2", features = ["derive"] }
clap_complete = "4.2.0"
clap_mangen = "0.2.10"
directories = "5.0.0"
flume = "0.10.14"
ignore = "0.4.20"
notify = "5.1.0"
once_cell = "1.17.1"
semver = "1.0.17"
serde = { version = "1.0.160", features = ["derive"] }
tabled = { version = "0.11.1", features = ["color", "derive"] }
tempfile = "3.5.0"
tokio = { version = "1.27.0", features = ["macros", "rt", "sync"] }
tokio-shutdown = "0.1.3"
toml = "0.7.3"
tower-http = { version = "0.4.0", features = ["fs"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
which = "4.4.0"
yansi = "0.5.1"

[dev-dependencies]
assert_fs = "1.0.13"
indoc = "2.0.1"

[profile.release]
lto = true
strip = true
