[package]
name = "wazzup"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"
description = "Very opinionated Rust WASM project builder"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]

[dependencies]
anyhow = "1.0.69"
axum = { version = "0.6.4", features = ["http2", "ws"] }
cargo-lock = "8.0.3"
clap = { version = "4.1.4", features = ["derive"] }
clap_complete = "4.1.1"
clap_mangen = "0.2.7"
directories = "4.0.1"
flume = "0.10.14"
ignore = "0.4.20"
notify = "5.1.0"
once_cell = "1.17.0"
semver = "1.0.16"
serde = { version = "1.0.152", features = ["derive"] }
tabled = { version = "0.10.0", features = ["color", "derive"] }
tempfile = "3.3.0"
tokio = { version = "1.25.0", features = ["macros", "rt", "sync"] }
tokio-shutdown = "0.1.3"
toml = "0.7.2"
tower-http = { version = "0.3.5", features = ["fs"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
which = "4.4.0"
yansi = "0.5.1"

[dev-dependencies]
assert_fs = "1.0.10"
indoc = "2.0.0"

[profile.release]
lto = true
strip = true
