[package]
name = "wazzup"
version = "0.4.1"
edition = "2021"
license = "AGPL-3.0-only"
description = "Very opinionated Rust WASM project builder"
homepage = "https://github.com/dnaka91/wazzup"
repository = "https://github.com/dnaka91/wazzup"
keywords = ["build-tool", "dev-server", "tauri", "wasm"]
categories = ["command-line-utilities", "development-tools", "wasm", "web-programming"]
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
include = ["src/**/*", "CHANGELOG.md", "LICENSE", "README.md"]

[dependencies]
axum = { version = "0.6.20", features = ["http2", "ws"] }
cargo-lock = "9.0.0"
clap = { version = "4.4.6", features = ["derive", "wrap_help"] }
clap_complete = "4.4.3"
clap_mangen = "0.2.14"
color-eyre = { version = "0.6.2", default-features = false }
directories = "5.0.1"
flume = "0.11.0"
ignore = "0.4.20"
minify-html = "0.11.1"
minify-js = "0.5.6"
notify = "6.1.1"
once_cell = "1.18.0"
semver = "1.0.20"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
serde_path_to_error = "0.1.14"
tabled = { version = "0.14.0", features = ["color", "derive"] }
tempfile = "3.8.0"
tokio = { version = "1.33.0", features = ["macros", "rt", "sync"] }
tokio-shutdown = "0.1.4"
toml = "0.8.2"
tower-http = { version = "0.4.4", features = ["fs"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
which = "4.4.2"
yansi = "1.0.0-rc.1"

[dev-dependencies]
assert_fs = "1.0.13"
indoc = "2.0.4"

[profile.release]
lto = true
strip = true
