[package]
name = "wazzup"
version = "0.3.1"
edition = "2021"
license = "AGPL-3.0-only"
description = "Very opinionated Rust WASM project builder"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]

[dependencies]
anyhow = "1.0.71"
axum = { version = "0.6.18", features = ["http2", "ws"] }
cargo-lock = "9.0.0"
clap = { version = "4.3.2", features = ["derive"] }
clap_complete = "4.3.1"
clap_mangen = "0.2.12"
directories = "5.0.1"
flume = "0.10.14"
ignore = "0.4.20"
minify-html = "0.11.1"
minify-js = "0.5.6"
notify = "6.0.0"
once_cell = "1.18.0"
semver = "1.0.17"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
tabled = { version = "0.12.1", features = ["color", "derive"] }
tempfile = "3.6.0"
tokio = { version = "1.28.2", features = ["macros", "rt", "sync"] }
tokio-shutdown = "0.1.4"
toml = "0.7.4"
tower-http = { version = "0.4.0", features = ["fs"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
which = "4.4.0"
yansi = "0.5.1"

[dev-dependencies]
assert_fs = "1.0.13"
indoc = "2.0.1"

[profile.release]
lto = true
strip = true
