targets = [
    { triple = "x86_64-unknown-linux-gnu" },
]

[licenses]
allow = [
    "CC0-1.0",
    "MPL-2.0",
]
allow-osi-fsf-free = "both"
exceptions = [
    { allow = ["AGPL-3.0"], name = "wazzup" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[bans]
skip = [
    { name = "aho-corasick", version = "0.7" },
    { name = "bitflags", version = "1" },
    { name = "hashbrown", version = "<0.14" },
    { name = "indexmap", version = "1" },
    { name = "minify-js", version = "0.4" },
    { name = "parse-js", version = "0.10" },
    { name = "socket2", version = "0.4" },
    { name = "syn", version = "1" },
    { name = "toml", version = "0.7" },
    { name = "toml_edit", version = "0.19" },
]
