[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
]

[advisories]
ignore = ["RUSTSEC-2024-0384"]

[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Zlib",
]
exceptions = [
    { allow = ["AGPL-3.0"], name = "wazzup" },
]

[bans]
skip = [
    "ahash@0.7",
    "aho-corasick@0.7",
    "bitflags@1",
    "hashbrown@<0.12",
    "hashbrown@<0.13",
    "hashbrown@<0.14",
    "heck@0.4",
    "itertools@0.10",
    "minify-js@0.5",
    "parse-js@0.17",
    "rustc-hash@1",
    "syn@1",
    "sync_wrapper@0.1",
]
skip-tree = [
]
