[workspace]
members = ["sample-two"]

[package]
name = "sample-one"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.84"
web-sys = { version = "0.3.61", features = [
    "Document",
    "Element",
    "HtmlElement",
    "Node",
    "Window",
] }
